server:
  port: 80
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sea_tide?serverTimezone=GMT%2B8
    username: root
    password: mysql
  mail:
    host: smtp.exmail.qq.com
    username: service@cciradih.top
    password: JAHihx2rtADtEgjF
